### ISSUE TITLE
Doesn't work in Lumen 5.2 

### ISSUE THREAD

**Issue by devat2s** [Waavi/url-shortener#4]
I have followed the instruction and configured the keys as well but it shows.

`InvalidResponseException in UrlShortener.php line 61:
Bit.ly returned status code "500" with message "MISSING_ARG_ACCESS_TOKEN"`

I think there may be issue with getting config values. Because if we hot code keys into vendor\waavi\url-shortner\src/Drivers/factory.php it works fine.. FYI
public function __construct(Config $config)
    {
        $googleApiKey   = $config->get('urlshortener.google.apikey');
        $bitlyUsername  = $config->get('urlshortener.bitly.username');
        $bitlyPassword  = $config->get('urlshortener.bitly.password');
        $connectTimeout = $config->get('urlshortener.connect_timeout');
        $timeout        = $config->get('urlshortener.timeout');

```
    $this->google = new Google($googleApiKey, $connectTimeout, $timeout);
    $this->bitly  = new Bitly($bitlyUsername, $bitlyPassword, $connectTimeout, $timeout);
}  dd($config) shows empty item
```

**Comment by sildraug** [comment]
I don't use Lumen, could you test it with the config helper instead of dependency injection?

config(

instead of

$config->get(
